server:
  port: 3306
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: lianjia
  username: root
  password: 123
  charset: utf8mb4
source:
  # 区域
  district:
    - nanhai
    - shunde
  # 二手房地址
  ershoufang: https://fs.lianjia.com/ershoufang/
  # 成交地址
  chengjiao: https://fs.lianjia.com/chengjiao/
