server:
  port: 3306
mysql:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: lianjia
  username: root
  password: 123
  charset: utf8mb4
elastic:
  selling: lianjia_selling
  sold: lianjia_sold
source:
  # 区域
  district:
    - nanhai
  # 二手房地址
  ershoufang: https://fs.lianjia.com/ershoufang/
  # 成交地址
  chengjiao: https://fs.lianjia.com/chengjiao/
